const mongoose = require("mongoose");
/**
 * - job desc schema : string
 * - resume text : string
 * - self desc : string
 *
 * - matchScore : number
 *
 * - technical questions - stored in array ->
 *                [{
 *                   question: ""
 *                   intention:""
 *                   answer:   ""
 *                }]
 * - behavioral questions- :
 *                [{
 *                   question: ""
 *                   intention:""
 *                   answer:   ""
 *                }]
 * - Skill gaps -:[{
 *                   skill: ""
 *                   severity: ""
 *                   type: string
 *                   enum:["low","medium","high"]
 *                }]
 * - prep plan - :
 *                [{
 *                   day: number
 *                   focus: string
 *                   tasks: [string]
 *                }]
 */

// This reusable schema stores one technical interview question generated by AI.
const technicalQuestionSchema = new mongoose.Schema(
  {
    // The actual question displayed on the report page.
    question: {
      type: String,
      required: [true, "Technical question is required"],
    },
    // Why this question matters for the job.
    intention: {
      type: String,
      required: [true, "Intention is required"],
    },
    // The suggested answer shown to the candidate.
    answer: {
      type: String,
      required: [true, "answer is required"],
    },
  },
  {
    // This keeps subdocuments simple because each question does not need its own ID.
    _id: false,
  },
);

// This reusable schema stores one behavioral question for soft-skill practice.
const behavioralQuestionSchema = new mongoose.Schema(
  {
    // The behavioral prompt displayed on the report page.
    question: {
      type: String,
      required: [true, "Behavorial question is required"],
    },
    // The reason the interviewer might ask this question.
    intention: {
      type: String,
      required: [true, "Intention is required"],
    },
    // The suggested response shown to the user.
    answer: {
      type: String,
      required: [true, "answer is required"],
    },
  },
  {
    // This keeps each behavioral item embedded directly inside the report.
    _id: false,
  },
);

// This reusable schema stores skills the candidate should improve.
const skillGapSchema = new mongoose.Schema(
  {
    // The name of the missing or weaker skill.
    skill: {
      type: String,
      required: [true, "Skill is required"],
    },
    // The urgency level controls how strongly the frontend highlights the gap.
    severity: {
      type: String,
      enum: ["low", "medium", "high"],
      required: [true, "Severity is required"],
    },
  },
  {
    _id: false,
  },
);

// This reusable schema stores one day of the candidate's practice plan.
const preparationPlanSchema = new mongoose.Schema({
  // The day number displayed in the roadmap.
  day: {
    type: Number,
    required: [true, "day is required"],
  },
  // The main topic for that practice day.
  focus: {
    type: String,
    required: [true, "focus is required"],
  },
  // A list of specific tasks the user should complete.
  tasks: [
    {
      type: String,
      required: [true, "tasks are required"],
    },
  ],
});

// This main schema stores the complete AI-generated report for one user.
const interviewReportSchema = new mongoose.Schema(
  {
    // The job post that the AI compared against the resume.
    jobDescription: {
      type: String,
      required: [true, "Job Description is required"],
    },
    // Plain text extracted from the uploaded PDF resume.
    resume: {
      type: String,
    },
    // Extra profile notes typed by the user.
    selfDescription: {
      type: String,
    },
    // A 0-100 score showing how well the candidate matches the job.
    matchScore: {
      type: Number,
      min: 0,
      max: 100,
    },
    // These arrays become the report tabs in the frontend.
    technicalQuestions: [technicalQuestionSchema],
    behavioralQuestions: [behavioralQuestionSchema],
    skillGaps: [skillGapSchema],
    preparationPlan: [preparationPlanSchema],
    // This connects the report to the logged-in user who created it.
    user:{
      type: mongoose.Schema.Types.ObjectId,
      ref: "users"
    }
  },
  {
    // This adds createdAt and updatedAt so reports can be sorted by newest first.
    timestamps: true,
  },
);

// This model lets controllers create and fetch interview reports in MongoDB.
const interviewReportModel = mongoose.model(
  "InterviewReport",
  interviewReportSchema,
);

// This export shares the report model with the interview controllers.
module.exports = interviewReportModel;
